library(dplyr)
library(tidyr)
library(lubridate)
library(pheatmap)
library(reshape2)
library(tibble)
library(cluster)
library(factoextra)
library(ggplot2)
library(pMineR)
library(DiagrammeR)

# Load data from either output.csv or filtered_output.csv
# both csv files are generated by the process_mining.R
# "output.csv" is the master file which contains all students' actions
# "filtered_output.csv" is a subset of output.csv based on user prompts (for a speicific user or grade range)
df <- read.csv("output.csv", stringsAsFactors = FALSE)
df$time_created <- ymd_hms(df$time_created)

transitions <- df %>%
  arrange(actor, session_id, time_created) %>%
  group_by(actor, session_id) %>%
  mutate(next_action = lead(action_code)) %>%
  ungroup() %>%
  filter(!is.na(next_action))

transition_matrix <- transitions %>%
  count(action_code, next_action) %>%
  pivot_wider(names_from = next_action, values_from = n, values_fill = 0)

transition_matrix <- as.data.frame(transition_matrix)
rownames(transition_matrix) <- transition_matrix$action_code
transition_matrix$action_code <- NULL

# Frequency Count Heatmap
pheatmap(as.matrix(transition_matrix),
         main = "Transition Frequency Heatmap",
         fontsize = 10,
         display_numbers = TRUE,
         number_format = "%.0f",
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         color = colorRampPalette(c("white", "darkred"))(100))

flat_z <- reshape2::melt(as.matrix(transition_matrix))
colnames(flat_z) <- c("from", "to", "count")
flat_z$z_score <- scale(flat_z$count)

# Z-score Heatmap
z_matrix <- reshape2::dcast(flat_z, from ~ to, value.var = "z_score", fill = 0)
rownames(z_matrix) <- z_matrix$from
z_matrix$from <- NULL

pheatmap(as.matrix(z_matrix),
         main = "Z-Score Heatmap",
         fontsize = 10,
         display_numbers = TRUE,
         number_format = "%.2f",
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         color = colorRampPalette(c("blue", "white", "red"))(100),
         breaks = seq(-max(abs(flat_z$z_score), na.rm = TRUE),
                      max(abs(flat_z$z_score), na.rm = TRUE),
                      length.out = 101))

# Filter transactions based on z-score
# Action pairs outside of specified score range will be dropped

flat_z$dropped <- ifelse(flat_z$z_score < 1, "Dropped", "Kept")
flat_z$valid <- ifelse(flat_z$dropped == "Dropped", NA, flat_z$count)

highlight_matrix <- reshape2::dcast(flat_z, from ~ to, value.var = "valid", fill = NA)
rownames(highlight_matrix) <- highlight_matrix$from
highlight_matrix$from <- NULL

text_matrix <- reshape2::dcast(flat_z, from ~ to, value.var = "dropped", fill = "")
rownames(text_matrix) <- text_matrix$from
text_matrix$from <- NULL
text_matrix <- apply(text_matrix, c(1, 2), function(x) if (x == "Kept") "✓" else if (x == "Dropped") "×" else "")

pheatmap(as.matrix(highlight_matrix),
         main = "Z-Filtered Transitions (✓ Kept, × Dropped)",
         display_numbers = text_matrix,
         number_color = "black",
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         color = colorRampPalette(c("white", "steelblue"))(100),
         na_col = "lightgray")


# Create full transition list with pair strings
flat_z <- flat_z %>%
  mutate(pair = paste(from, to, sep = " → "))

# Extract dropped and kept transitions
dropped_transitions <- flat_z %>%
  filter(dropped == "Dropped") %>%
  select(from, to, count, z_score, pair) %>%
  arrange(z_score)

kept_transitions <- flat_z %>%
  filter(dropped == "Kept") %>%
  select(from, to, count, z_score, pair) %>%
  arrange(desc(z_score))

# Print summaries for debugging
cat("🔻 Total dropped transitions:", nrow(dropped_transitions), "\n")
print(head(dropped_transitions, 5))

cat("Total kept transitions:", nrow(kept_transitions), "\n")
print(head(kept_transitions, 5))

# Extract pair strings for later filtering
dropped_pairs <- dropped_transitions$pair
kept_pairs <- kept_transitions$pair

# Build vectors for kepted actions
kept_actions <- unique(c(flat_z$from[flat_z$dropped == "Kept"],
                         flat_z$to[flat_z$dropped == "Kept"]))

actor_vectors <- df %>%
  filter(action_code %in% kept_actions) %>%
  group_by(actor, action_code) %>%
  summarise(count = n(), .groups = "drop") %>%
  pivot_wider(names_from = action_code, values_from = count, values_fill = 0)

X <- actor_vectors %>%
  column_to_rownames("actor")

# Clean for clustering
X <- X[complete.cases(X), ]
X <- X[!apply(X, 1, function(row) any(is.nan(row) | is.infinite(row))), ]
X <- X[rowSums(X) > 0, ]

# Elbow Plot for K Selection
fviz_nbclust(X, kmeans, method = "wss", k.max = 10) +
  labs(title = "Elbow Method")

set.seed(42)

#Replace k_best based on the elbow plot
k_best <- 3  
km_result <- kmeans(X, centers = k_best, nstart = 25)

# Create actor-to-cluster mapping
actor_clusters <- tibble(
  actor = rownames(X),
  cluster = km_result$cluster
)

df$actor <- as.character(df$actor)
actor_clusters$actor <- as.character(actor_clusters$actor)

# Merge cluster into original df
df_with_clusters <- df %>%
  left_join(actor_clusters, by = "actor")

# Save new dataset
write.csv(df_with_clusters, "output_clustered.csv", row.names = FALSE)

# Drop unwanted transactions
df_with_clusters <- df_with_clusters %>%
  arrange(actor, session_id, time_created) %>%
  group_by(actor, session_id) %>%
  mutate(
    next_action = lead(action_code),
    transition_pair = paste(action_code, next_action, sep = " → "), 
    drop_flag = transition_pair %in% dropped_pairs
  ) %>%
  ungroup()

# Remove the 'from' action row of dropped transitions
df_pruned <- df_with_clusters %>%
  filter(!drop_flag) %>%
  select(-drop_flag, -next_action, -transition_pair)

# Save the cleaned version (dropped all unwanted action sequences)
write.csv(df_pruned, "output_clustered_cleaned.csv", row.names = FALSE)

# pMineR Markov Plot 
# Load cleaned dataset from step 7
# Substitue with "output_clustered.csv" if don't want to drop any actions
df_pruned <- read.csv("output_clustered_cleaned.csv", stringsAsFactors = FALSE)

# Ensure timestamp is in correct format
df_pruned$time_created <- ymd_hms(df_pruned$time_created)

# Filter only valid rows for Markov modeling
df_plot_ready <- df_pruned %>%
  filter(!is.na(cluster), !is.na(srl_subcategory)) %>%
  select(session_id, time_created, srl_subcategory, cluster)

# Loop over clusters and plot each Markov model
for (target_cluster in sort(unique(df_plot_ready$cluster))) {
  cat("Drawing Markov model for Cluster", target_cluster, "\n")
  
  cluster_data <- df_plot_ready %>%
    filter(cluster == target_cluster) %>%
    rename(CaseID = session_id,
           Timestamp = time_created,
           Event = srl_subcategory)
  
  cluster_data$Timestamp <- ymd_hms(cluster_data$Timestamp)
  
  if (nrow(cluster_data) > 0) {
    objDL <- dataLoader(verbose.mode = FALSE)
    objDL$load.data.frame(
      mydata = cluster_data,
      IDName = "CaseID",
      EVENTName = "Event",
      dateColumnName = "Timestamp",
      format.column.date = "%Y-%m-%d %H:%M:%S"
    )
    
    fomm <- firstOrderMarkovModel(verbose.mode = FALSE)
    fomm$loadDataset(dataList = objDL$getData())
    fomm$trainModel()
    
    # Draw using DiagrammeR
    print(grViz(fomm$plot(giveItBack = TRUE)))
  } else {
    cat("Cluster", target_cluster, "has no valid data.\n")
  }
}

